- name: neu
  left:	 02
  right: 02
  mouth: 08
- name: ta1 
  left:  -- 
  right: -- 
  mouth: 08
- name: ta2
  left:  -- 
  right: --
  mouth: 16
- name: hap 
  left:  02 
  right: 02
  mouth: 38
- name: sad 
  left:  02 
  right: 02 
  mouth: 0B
- name: sur 
  left:  08
  right: 08 
  mouth: 16
- name: evi 
  left:  01 
  right: 01 
  mouth: 38
- name: ang 
  left:  01 
  right: 01 
  mouth: 0B
- name: shy 
  left:  04 
  right: 04 
  mouth: 38
- name: cun 
  left:  04 
  right: 01 
  mouth: 38
